name = "Moonshine PC"
address = "::"

[[applications]]
title = "Desktop"

# [[applications]]
# title = "Desktop low resolution"

[webserver]
port = 47989
port_https = 47990
certificate_chain = "./cert/cert.pem"
private_key = "./cert/key.pem"

[session]
fps = 60
video_quality = "Fastest"
codec = "H264"

[rtsp]
port = 48010
