name = "Moonshine PC"
address = "0.0.0.0"
port = 47989

[[applications]]
title = "Desktop"

# [[applications]]
# title = "Desktop low resolution"

[tls]
port = 47984
certificate_chain = "./cert/cert.pem"
private_key = "./cert/key.pem"
