name = "Moonshine PC"
address = "::"
port = 47989

[[applications]]
title = "Desktop"

# [[applications]]
# title = "Desktop low resolution"

[tls]
port = 47984
certificate_chain = "./cert/cert.pem"
private_key = "./cert/key.pem"

[session]
fps = 60
video_quality = "Fastest"
codec = "H264"
