name = "Moonshine PC"
address = "127.0.0.1"

[[applications]]
title = "Desktop"

[webserver]
port = 47989
port_https = 47990
certificate_chain = "./cert/cert.pem"
private_key = "./cert/key.pem"

[session]
fps = 60
# video_quality = "Fastest"
codec = "libx264"

[rtsp]
port = 48010
