name = "Moonshine Grietje"
address = "0.0.0.0"

[[application]]
title = "Desktop"

[[application_scanner]]
type = "steam"
library = "$HOME/.local/share/Steam"
run_before = [
	["$HOME/.local/bin/resolution", "{width}", "{height}"],
	["/usr/bin/steam", "steam://rungameid/{game_id}"],
]
run_after = [
	["$HOME/.local/bin/resolution"],
]

[webserver]
port = 47989
port_https = 47984
certificate_chain = "./cert/cert.pem"
private_key = "./cert/key.pem"

[stream]
port = 48010

[stream.video]
port = 47998
codec_h264 = "h264_nvenc"
codec_hevc = "hevc_nvenc"
fec_percentage = 20

[stream.audio]
port = 48000

[stream.control]
port = 47999
