name = "Moonshine PC"
address = "0.0.0.0"

[[applications]]
title = "Desktop"

[webserver]
port = 47989
port_https = 47984
certificate_chain = "./cert/cert.pem"
private_key = "./cert/key.pem"

[stream]
port = 48010

[stream.video]
port = 47998
codec = "libx264"
fec_percentage = 20

[stream.audio]
port = 48000

[stream.control]
port = 47999
