[package]
name = "moonshine"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.2"
nvfbc = "0.1.2"
ffmpeg-sys = { path = "../ffmpeg-sys" }
zeroconf = "0.10.5"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros", "net"] }
serde = "1.0.140"
openssl = "0.10.41"
hex = "0.4.3"
hyper = { version = "0.14.20", features = ["server", "http1"] }
url = "2.2.2"
