[package]
name = "moonshine"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
# ffmpeg-sys = { path = "../ffmpeg-sys" }
hex = "0.4.3"
hyper = { version = "0.14.20", features = ["server", "http1", "tcp"] }
image = "0.24.2"
log = "0.4.17"
# nvfbc = "0.1.2"
openssl = "0.10.41"
serde = "1.0.140"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros", "net"] }
tokio-openssl = "0.6.3"
url = "2.2.2"
zeroconf = "0.10.5"
