[package]
name = "moonshine"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.2"
nvfbc = { path = "../../nvfbc-rs/nvfbc" }
rustacuda = "0.1.3"
rustacuda_core = "0.1.2"
rustacuda_derive = "0.1.2"
