[package]
name = "ffmpeg-stream-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-sys = { path = "../ffmpeg-sys" }
nvfbc = "0.1.2"
