name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo pacman -Syyuu --noconfirm --needed clang cmake rust avahi cuda ffmpeg gcc-libs glibc libpulse nvidia-utils openssl opus

    - name: Build
      run: cargo build --release

    - name: Compress
      run: tar caf "./moonshine.tar.xz" -C ./target/release moonshine

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "./moonshine.tar.xz"
