name: Rust

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            sudo add-apt-repository ppa:graphics-drivers/ppa
            sudo apt update
            sudo apt install -y libnvidia-fbc1-550 nvidia-cuda-toolkit pkg-config libjack-dev libpulse-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libavahi-client-dev

        - name: Build
          run: cargo build --verbose

        - name: Run tests
          run: cargo test --verbose
